version: '3.9'
services:
  web:
    image: cnn-image:1.0
    container_name: web-container
    build: .
    ports:
      - "${CNN_GUNICORN_PORT:-5000}:5000"
    volumes:
      - type: bind
        source: ./models
        target: /cnn/models
    working_dir: /cnn/src/webapp
    command: gunicorn --timeout 90 --threads ${CNN_GUNICORN_THREADS:-8} --worker-class gthread --bind 0.0.0.0:5000 classifier:app
  obtain:
    image: cnn-image:1.0
    container_name: obtain-container
    build: .
    volumes:
      - type: bind
        source: ./data
        target: /cnn/data
      - type: bind
        source: ./metadata
        target: /cnn/metadata
    working_dir: /cnn/src/scripts
    command: python obtain.py ${CNN_OBTAIN_JSON:-obtain.json}
  augment:
    image: cnn-image:1.0
    container_name: augment-container
    build: .
    volumes:
      - type: bind
        source: ./data
        target: /cnn/data
      - type: bind
        source: ./metadata
        target: /cnn/metadata
    working_dir: /cnn/src/scripts
    command: python augment.py ${CNN_AUGMENT_JSON:-augment.json}
  train:
    image: cnn-image:1.0
    container_name: train-container
    build: .
    ports:
      - "${CNN_NOTEBOOK_PORT:-5001}:5001"
    volumes:
      - type: bind
        source: ./data
        target: /cnn/data
      - type: bind
        source: ./models
        target: /cnn/models
      - type: bind
        source: ./logs
        target: /cnn/logs
      - type: bind
        source: ./plots
        target: /cnn/plots
    working_dir: /cnn/src/notebooks
    command: jupyter notebook --ip 0.0.0.0 --port 5001 --allow-root
  tensorboard:
    image: cnn-image:1.0
    container_name: tensorboard-container
    build: .
    ports:
      - "${CNN_TENSORBOARD_PORT:-5002}:5002"
    volumes:
      - type: bind
        source: ./logs
        target: /cnn/logs
    working_dir: /cnn
    command: sh -c "rm -rf logs/* && tensorboard --host 0.0.0.0 --port 5002 --logdir logs"